- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include_tasks: tasks/ssh.yml
      tags:
        - dotfiles
        - install
        - ssh
    - include_tasks: tasks/git-setup.yml
      tags:
        - git-personal
        - git-datanumia
    - include_tasks: tasks/core-setup.yml
      tags:
        - install
        - neovim
        - core
    # - include_tasks: tasks/node-setup.yml
    # - include_tasks: tasks/npm-packages.yml
    - include_tasks: tasks/zsh-setup.yml
      tags:
        - install
        - productivity
        - dotfiles
        - zsh
    - include_tasks: tasks/slack-setup.yml
      tags:
        - install
        - slack
    - include_tasks: tasks/nvim-setup.yml
      tags:
        - install
        - neovim
    - include_tasks: tasks/lazy-git.yml
      tags:
        - install
        - lazygit 
    - include_tasks: tasks/dotfiles.yml
      tags:
        - install
        - dotfiles
        - stow
    - include_tasks: tasks/python-setup.yml
      tags:
        - install
        - python 
    - include_tasks: tasks/productivity-tools.yml
      tags:
        - install
        - productivity 
    - include_tasks: tasks/zotero-setup.yml
      tags:
        - zotero
        - install
    - include_tasks: tasks/personal-projects.yml
      tags:
        - install
        - dotfiles
        - neovim
        - personal-project
  handlers:
    - name: Update desktop database
      command: update-desktop-database ~/.local/share/applications
      listen: "desktop database update"
