- name: lazygit exists
  stat:
    path: "/usr/local/bin/lazygit"
    # path: "{{ lookup('env', 'HOME') }}/lazygit"
  register: lazygit 
  tags:
    - install
    - lazygit

- name: Fetch the latest release of lazygit
  uri:
    url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
    return_content: yes
  register: lazygit_release
  tags:
    - install
    - lazygit

- name: Download the latest lazygit tarball
  get_url:
    url: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_release.json.tag_name[1:] }}_Linux_x86_64.tar.gz"
    dest: "lazygit.tar.gz"
  tags:
    - install
    - lazygit

- name: Extract lazygit from tarball
  unarchive:
    src: "lazygit.tar.gz"
    dest: "lazygit"
    remote_src: yes
    extra_opts: [--strip-components=1]
    # creates: "lazygit"
  tags:
    - install
    - lazygit

- name: Install lazygit binary to /usr/local/bin
  become: true
  command: install lazygit /usr/local/bin
  tags:
    - install
    - lazygit

- name: clean lazygit 
  shell: rm lazygit.tar.gz
  tags:
    - install
    - lazygit
