- name: Ensure required tools are installed
  apt:
    name:
      - software-properties-common
      - apt-transport-https
    state: present
  become: yes
  tags:
    - install
    - neovim

- name: Remove existing Neovim apt package
  apt:
    name: neovim
    state: absent
    purge: yes
  become: yes
  tags:
    - install
    - neovim

- name: Remove manually installed Neovim binaries
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/bin/nvim
    - /usr/local/nvim-linux64
    - /usr/local/src/neovim
  become: yes
  tags:
    - install
    - neovim

- name: Remove Neovim configuration and plugin data
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ lookup('env', 'HOME') }}/.config/nvim"
    - "{{ lookup('env', 'HOME') }}/.local/share/nvim/lazy"
    - "{{ lookup('env', 'HOME') }}/.config/nvim/lazy-lock.json"
  tags:
    - install
    - neovim

- name: Add Neovim PPA
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'
    state: present
  become: yes
  tags:
    - install
    - neovim

- name: Install Neovim from PPA
  apt:
    name: neovim
    state: latest
  become: yes
  tags:
    - install
    - neovim

- name: Check installed Neovim version
  command: nvim --version
  register: nvim_version
  changed_when: false
  tags:
    - install
    - neovim

- name: Display Neovim version
  debug:
    msg: "Installed Neovim version: {{ nvim_version.stdout_lines[0] }}"
  tags:
    - install
    - neovim

- name: Install Neovim configuration
  ansible.builtin.git:
    repo: 'git@github.com:PaulCalot/kickstart.nvim.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    accept_hostkey: yes
  tags:
    - install
    - neovim
