- name: neovim config exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim"
  register: neovim
  tags:
    - install
    - neovim
- name: neovim config installation 
  ansible.builtin.git:
    repo: 'git@github.com:PaulCalot/kickstart.nvim.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
  tags:
    - install
    - neovim
  when: neovim.stat.exists == False
