- name: Ensure build dependencies are installed
  apt:
    name:
      - ninja-build
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip
      - curl
    state: present
  become: yes
  tags:
    - install
    - neovim

- name: Check if Neovim is already installed
  command: nvim --version
  register: nvim_check
  ignore_errors: yes
  tags:
    - install
    - neovim

- name: Clone Neovim repository
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: /usr/local/src/neovim
    version: 'v0.9.5'
    force: yes
    accept_hostkey: yes
    update: yes
  when: nvim_check.rc != 0
  become: yes
  tags:
    - install
    - neovim

- name: Build Neovim from source
  shell: |
    make CMAKE_BUILD_TYPE=Release
  args:
    chdir: /usr/local/src/neovim
  when: nvim_check.rc != 0
  become: yes
  tags:
    - install
    - neovim

- name: Install Neovim
  shell: |
    make install
  args:
    chdir: /usr/local/src/neovim
  when: nvim_check.rc != 0
  become: yes
  tags:
    - install
    - neovim

- name: neovim config exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim"
  register: neovim
  tags:
    - install
    - neovim

- name: neovim config installation 
  ansible.builtin.git:
    repo: 'git@github.com:PaulCalot/kickstart.nvim.git'
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
  tags:
    - install
    - neovim
  when: neovim.stat.exists == False
