# pas sûr de comprendre s'il y a des choses que je devrais modifier, en particulier la copie du .ssh/config
# je pense que le config sera géré dans le deuxième étape ici
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
# - name: Set authorized key from files
#   authorized_key:
#     user: "{{ lookup('env', 'USER') }}"
#     state: present
#     key: "{{ lookup('file', item) }}"
#   loop: "{{ lookup('fileglob', lookup('env', 'HOME') + '/.ssh/*.pub', wantlist=True) }}"
# - name: Set authorized key took from file
#   authorized_key:
#     user: "{{ lookup('env', 'USER') }}"
#     state: present
#       # pourquoi id_rsa et pas *.pub ?
#     key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
#   with_fileglob:
#   - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
