# TODO coulds be cleaned up a bit I believe
- name: zotero exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/opt/zotero"
  register: zotero
  tags:
    - install
    - zotero

- name: Create zotero directory if it does not exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/opt/zotero"
    state: directory
    mode: '0755'
  when: zotero.stat.exists == False

- name: Download and extract Zotero tarball
  become: true
  unarchive:
    src: "https://www.zotero.org/download/client/dl?channel=release&platform=linux-x86_64&version=6.0.35"
    dest: ~/opt/zotero
    remote_src: yes
    extra_opts: [--strip-components=1]
  tags:
    - install
    - zotero
  when: zotero.stat.exists == False

- name: Set launcher icon
  become: true
  command: ~/opt/zotero/set_launcher_icon
  tags:
    - install
    - zotero
  when: zotero.stat.exists == False

- name: Ensure ~/.local/share/applications directory exists
  become: true
  file:
    path: ~/.local/share/applications
    state: directory
    mode: '0755'
  tags:
    - install
    - zotero
  when: zotero.stat.exists == False

- name: Create symlink for Zotero desktop file
  become: true
  file:
    src: ~/opt/zotero/zotero.desktop
    dest: ~/.local/share/applications/zotero.desktop
    state: link
  tags:
    - install
    - zotero
  when: zotero.stat.exists == False
